module.exports = {
  SET_ASSET_RATE: 'SET_ASSET_RATE',
  SET_GLOBAL_CAPACITY_RATIO: 'SET_GLOBAL_CAPACITY_RATIO',
  SET_PRODUCT: 'SET_PRODUCT',
  SET_POOL_PRODUCT: 'SET_POOL_PRODUCT',
  SET_TRANCHE_ID: 'SET_TRANCHE_ID',
};
