module.exports = {
  SET_STATE: 'SET_STATE',
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_PRODUCT: 'SET_PRODUCT',
  SET_PRODUCT_STAKING_POOL: 'SET_PRODUCT_STAKING_POOL',
  SET_ALL_PRODUCT_STAKING_POOLS: 'SET_ALL_PRODUCT_STAKING_POOLS',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  REMOVE_STAKING_POOL: 'REMOVE_STAKING_POOL',
  SET_TRANCHE_ID: 'SET_TRANCHE_ID',
};
