name: Merge to dev or hotfix

on:
  push:
    branches:
      - dev
      - hotfix

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  reset-release-candidate:
    uses: NexusMutual/workflows/.github/workflows/reset.yml@master
    with:
      target-ref: release-candidate
      base-ref: ${{ github.ref_name }}
      environment: production
    secrets:
      DEPLOYER_APP_ID: ${{ secrets.DEPLOYER_APP_ID }}
      DEPLOYER_APP_PK: ${{ secrets.DEPLOYER_APP_PK }}

  bump-version:
    needs: reset-release-candidate
    uses: NexusMutual/workflows/.github/workflows/bump.yml@master
    with:
      ref: 'release-candidate'
      bump-command: GITHUB_REF=refs/heads/release-candidate npx semantic-release --dry-run --no-ci 
      environment: production
    secrets:
      DEPLOYER_APP_ID: ${{ secrets.DEPLOYER_APP_ID }}
      DEPLOYER_APP_PK : ${{ secrets.DEPLOYER_APP_PK }}

  build:
    needs: bump-version
    uses: NexusMutual/workflows/.github/workflows/build.yml@master
    with:
      ref: 'release-candidate'
      environment: production
      image: ${{ github.repository }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  tag-image:
    needs: build
    uses: NexusMutual/workflows/.github/workflows/tag-image.yml@master
    with:
      environment: production
      image: ${{ github.repository }}
      ref: 'release-candidate'
      target-tag: ${{ github.ref_name == 'master' && 'latest' || 'staging' }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
