name: Merge to dev or hotfix

on:
  push:
    branches:
      - dev
      - hotfix

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  reset-release-candidate:
    uses: NexusMutual/workflows/.github/workflows/reset.yml@master
    with:
      target-ref: release-candidate
      base-ref: ${{ github.ref_name }}
      environment: production
    secrets:
      DEPLOYER_APP_ID: ${{ secrets.DEPLOYER_APP_ID }}
      DEPLOYER_APP_PK: ${{ secrets.DEPLOYER_APP_PK }}

  bump-version:
    needs: reset-release-candidate
    uses: NexusMutual/workflows/.github/workflows/bump.yml@master
    with:
      ref: 'release-candidate'
      bump-command: |
        BUMP=$(timeout 5s npx conventional-recommended-bump --config .github/config/conventional-bump-setup.js --verbose | head -n1) || true
        if [ ! -z "$BUMP" ] && [[ "$BUMP" != *"No version bump needed"* ]]; then
          npm version "$BUMP" --no-git-tag-version
        else
          echo "No version bump"
        fi
      environment: production
    secrets:
      DEPLOYER_APP_ID: ${{ secrets.DEPLOYER_APP_ID }}
      DEPLOYER_APP_PK : ${{ secrets.DEPLOYER_APP_PK }}

  build:
    needs: bump-version
    uses: NexusMutual/workflows/.github/workflows/build.yml@master
    with:
      ref: 'release-candidate'
      environment: production
      image: ${{ github.repository }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  tag-image:
    needs: build
    uses: NexusMutual/workflows/.github/workflows/tag-image.yml@master
    with:
      environment: production
      image: ${{ github.repository }}
      ref: 'release-candidate'
      target-tag: ${{ github.ref_name == 'master' && 'latest' || 'staging' }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
