name: Merge to dev or hotfix

on:
  pull_request:
    types:
      - closed
    branches:
      - dev
      - hotfix
  workflow_call:
    inputs:
      branch:
        description: 'Target branch (dev or hotfix)'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22

jobs:
  needs-version-bump:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_call' || github.event.pull_request.merged == true
    outputs:
      needs_bump: ${{ steps.check-bump.outputs.needs_bump }}
      bump_type: ${{ steps.check-bump.outputs.bump_type }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch || github.ref_name }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts --prefer-offline --no-audit --no-fund

      - id: check-bump
        run: |
          echo "Running conventional-recommended-bump to check for version changes..."
          BUMP=$(timeout 5s npx conventional-recommended-bump --config .github/config/conventional-bump-setup.js) || true

          if [ ! -z "$BUMP" ] && [[ "$BUMP" != *"No version bump needed"* ]]; then
            echo "A version bump is needed: '$BUMP'"
            echo "needs_bump=true" >> $GITHUB_OUTPUT
            echo "bump_type=${BUMP}" >> $GITHUB_OUTPUT
          else
            echo "No version bump needed."
            echo "needs_bump=false" >> $GITHUB_OUTPUT
          fi

  reset-release-candidate:
    needs: needs-version-bump
    if: (github.event_name == 'workflow_call' || github.event.pull_request.merged == true) && needs.needs-version-bump.outputs.needs_bump == 'true'
    uses: NexusMutual/workflows/.github/workflows/reset.yml@master
    with:
      target-ref: release-candidate
      base-ref: ${{ inputs.branch || github.ref_name }}
      environment: production
    secrets:
      DEPLOYER_APP_ID: ${{ secrets.DEPLOYER_APP_ID }}
      DEPLOYER_APP_PK: ${{ secrets.DEPLOYER_APP_PK }}

  bump-version:
    needs: [needs-version-bump, reset-release-candidate]
    if: (github.event_name == 'workflow_call' || github.event.pull_request.merged == true) && needs.needs-version-bump.outputs.needs_bump == 'true'
    uses: NexusMutual/workflows/.github/workflows/bump.yml@master
    with:
      ref: 'release-candidate'
      bump-command: |
        echo 'executing npm version bump: ' "${{ needs.needs-version-bump.outputs.bump_type }}"
        npm version "${{ needs.needs-version-bump.outputs.bump_type }}" --no-git-tag-version
      environment: production
    secrets:
      DEPLOYER_APP_ID: ${{ secrets.DEPLOYER_APP_ID }}
      DEPLOYER_APP_PK: ${{ secrets.DEPLOYER_APP_PK }}

  build:
    needs: [needs-version-bump, bump-version]
    if: (github.event_name == 'workflow_call' || github.event.pull_request.merged == true) && needs.needs-version-bump.outputs.needs_bump == 'true'
    uses: NexusMutual/workflows/.github/workflows/build.yml@master
    with:
      ref: 'release-candidate'
      environment: production
      image: ${{ github.repository }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  tag-image:
    needs: [needs-version-bump, build]
    if: (github.event_name == 'workflow_call' || github.event.pull_request.merged == true) && needs.needs-version-bump.outputs.needs_bump == 'true'
    uses: NexusMutual/workflows/.github/workflows/tag-image.yml@master
    with:
      environment: production
      image: ${{ github.repository }}
      ref: 'release-candidate'
      target-tag: ${{ github.ref_name == 'master' && 'latest' || 'staging' }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
