name: pull-request
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '22'
  LOG_LEVEL: 'SILENCE'

jobs:
  checks:
    # Skip CI for draft PRs since this workflow is triggered once its review for review
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts --prefer-offline --no-audit --no-fund

      - name: Lint
        run: npm run lint

      - name: TypeScript build check
        run: npm run ts:build

      - name: Check types and typescript
        run: npm run ts:check

      - name: Test
        run: npm test
